export enum EStatusCodeError {
  UNKNOWN_ERROR,

  USER_NOT_FOUND_ERROR,
  USER_EXISTS_ERROR,
  USER_IS_INACTIVE_ERROR,
  USER_EMAIL_ALREADY_EXIST_ERROR,
  USER_ACTIVE_ERROR,
  USER_CREATE_FIREBASE_ACCOUNT_ERROR,

  POST_CAN_NOT_MODIFY,
  POST_NOT_FOUND_ERROR,

  CONVERSATION_CAN_NOT_CREATE_CONVERSATION,
  CONVERSATION_NOT_FOUND_ERROR,
}
